jenkins:
  systemMessage: "Welcome to Jenkins configured with JCasC!"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy: "loggedInUsersCanDoAnything"
  jobs:
    - script: >
        pipelineJob('test-job') {
          definition {
            cps {
              script("""
                pipeline {
                  agent any
                  stages {
                    stage('Build') {
                      steps {
                        sh 'echo Hello, Jenkins!'
                      }
                    }
                  }
                }
              """.stripIndent())
            }
          }
        }
tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"
